[[test]]
test_name = "1-hello"
test_file = "1-hello.js"
expected_output = "hello"
expected_response_status = 200

[[test]]
test_name = "2-blob"
test_file = "2-blob.js"
expected_output = "Hello, world!"
expected_response_status = 200

[[test]]
test_name = "3-headers"
test_file = "3-request.js"
expected_output = "Hello, world!"
expected_response_status = 200

[[test]]
test_name = "4-request"
test_file = "4-request.js"
expected_output = "Hello, world!"
expected_response_status = 200
